Генерация данных
htmlacademy-javascript/2067857-keksobooking-26 pull request #4
Opened 2022-06-16 13:01 UTC by YaninaGazizovna

2022-06-20 04:54 UTC, Manyaka requested changes

2022-06-20 04:54 UTC, Manyaka commented on js/main.js
> +    for (let i = 0; i <= 10; i++) {
10 - это что?

2022-06-20 04:54 UTC, Manyaka commented on js/main.js
> +  avatar: function () {
вынеси функцию создания урла для аватарки отдельно

2022-06-20 04:54 UTC, Manyaka commented on js/main.js
> +const author = {
это странная переменная - для чего ты её используешь?

2022-06-20 04:54 UTC, Manyaka commented on js/main.js
> +  return arr.map((i) => [Math.random(),i]).sort().map((i) => i[1]);
что ты тут делаешь?

2022-06-20 04:54 UTC, Manyaka commented on js/main.js
> +
пройдись бьютифаем, или преттиером, надо убрать лишние пустые строки

2022-06-20 05:07 UTC, YaninaGazizovna commented on js/main.js
> +  return arr.map((i) => [Math.random(),i]).sort().map((i) => i[1]);
Данная функция является вспомогательной, предназначена для перемешивания значений массива в случаном порядке, используется ниже в коде с методом splice (для удаления значений в случайном порядке)

2022-06-20 05:09 UTC, YaninaGazizovna commented on js/main.js
> +    for (let i = 0; i <= 10; i++) {
10 - это счетчик - количество  юзеров, заданное по тз

2022-06-20 05:11 UTC, YaninaGazizovna commented on js/main.js
> +const author = {
данная переменная - это объект (по тз), где ключ аватар со значением функцией

2022-06-20 05:38 UTC, Manyaka commented on js/main.js
> +  return arr.map((i) => [Math.random(),i]).sort().map((i) => i[1]);
Ага, а что конкретно ты тут делаешь, опиши по этапно, как это работает, что ты даешь на входе, что получаешь на выходе?

2022-06-20 05:40 UTC, Manyaka commented on js/main.js
> +    for (let i = 0; i <= 10; i++) {
ага, и где у тебя в коде еще встречается количество юзеров, заданное по тз?

2022-06-20 05:43 UTC, Manyaka commented on js/main.js
> +const author = {
ага, тогда тебе надо чтобы автор попал в возвращаемый объект в createProposal.

2022-06-20 06:57 UTC, YaninaGazizovna commented on js/main.js
> +  return arr.map((i) => [Math.random(),i]).sort().map((i) => i[1]);
на первой итерации, с помощью метода map, создаем новый массив, где первый элемент случайное значение, второе i(элемент исходного массива).
на второй итерации,  с помощью метода sort, сортируем массив (сортируется по первому элементу массива).
на третье итерации, c помощью метода map возвращаем значение i первым элементом массива.
итог - перемешанный новый массив - удовлетворяет требованию случайных значений

2022-06-20 06:57 UTC, YaninaGazizovna commented on js/main.js
> +    for (let i = 0; i <= 10; i++) {
дилетантская ошибка

2022-06-21 04:58 UTC, Manyaka requested changes

2022-06-21 04:58 UTC, Manyaka commented on js/main.js
> +};
интересно, это у нас что?

2022-06-21 04:58 UTC, Manyaka commented on js/main.js
> +    description: Offer.DESCRIPTION,
как думаешь, возможно ли так, что эти свойства объекта, должны быть в ключе offer? 

> offer, объект — содержит информацию об объявлении. Состоит из полей:

и там ещё два нижних фичерез и фотос?

2022-06-21 04:58 UTC, Manyaka commented on js/main.js
> +    avatar: Author.AVATAR[randomAvatarIndex],
как думаешь, если учесть комент выше, то может ли свойство avatar быть в ключе 

> author, объект — описывает автора. Содержит одно поле:

?

2022-06-21 05:19 UTC, YaninaGazizovna commented on js/main.js
> +    avatar: Author.AVATAR[randomAvatarIndex],
завернула в объект

2022-06-21 05:19 UTC, YaninaGazizovna commented on js/main.js
> +    description: Offer.DESCRIPTION,
завернула в объект

2022-06-21 05:20 UTC, YaninaGazizovna commented on js/main.js
> +};
объект, где значение ключа - функция

2022-06-22 05:58 UTC, Manyaka commented on js/main.js
> +};
ага, почему объект назван как перечисление? В нём же ничего не перечисляется.
Почему, если значение ключа - функция, а значит - вычисляемое значение, ключ назван как константа?
Ну и самое главное - в чём смысл этого объекта?

2022-06-22 06:16 UTC, Manyaka requested changes

2022-06-22 06:16 UTC, Manyaka commented on js/main.js
> +  ],
раз это так и не используется, то можно и удалить, чтобы глаза не мозолило

2022-06-22 06:16 UTC, Manyaka commented on js/main.js
> +const createProposal = function () {
https://up.htmlacademy.ru/javascript/26/criteries#d5

>  Все функции объявлены единообразно.

у тебя смешались стили, так что тебе надо поправить, посмотри в критерии как. Если тебе нравится использовать function declaration, то можешь и тут тогда поправить

2022-06-22 06:16 UTC, Manyaka commented on js/main.js
> +function getMixArr(arr) {
```suggestion
function getMixArray(array) {
```

нет смысла экономить на спичках и писать сокращённо, сокращает за тебя обфускатор и минимизатор, а тебе надо писать понятнее некуда, тк тебя читает человек.

2022-06-22 06:16 UTC, Manyaka commented on js/main.js
> +  return arr.map((i) => [Math.random(),i]).sort().map((i) => i[1]);
собери этот массив заранее, не в ретурне, и разложи его на три метода, которые ты использовала, назвав переменные соответственно:

> на первой итерации, с помощью метода map, создаем новый массив, где первый элемент случайное значение, второе i(элемент исходного массива).
на второй итерации, с помощью метода sort, сортируем массив (сортируется по первому элементу массива).
на третье итерации, c помощью метода map возвращаем значение i первым элементом массива.
итог - перемешанный новый массив - удовлетворяет требованию случайных значений

ну и ессно, назвав `i` - по-нормальному

2022-06-22 06:16 UTC, Manyaka commented on js/main.js
> +  const getRandomPhotosArray = getMixArr(Offer.PHOTOS).splice(getRandomIntInclusive(0, Offer.PHOTOS.length - 1));
не очень, конечно, прикольно, что тут 2 действия: получение рандомного массив и отрезание от него рандомного куска, ну пусть будет. Оптимально - 1 действие. Всё что больше 1-го действия выносим в отдельную функцию

2022-06-22 06:51 UTC, YaninaGazizovna commented on js/main.js
> +function getMixArr(arr) {
done

2022-06-22 06:51 UTC, YaninaGazizovna commented on js/main.js
> +const createProposal = function () {
done

2022-06-22 06:51 UTC, YaninaGazizovna commented on js/main.js
> +  ],
done

2022-06-22 08:05 UTC, YaninaGazizovna commented on js/main.js
> +  return arr.map((i) => [Math.random(),i]).sort().map((i) => i[1]);
done

2022-06-23 05:48 UTC, merged