Module7 task1
htmlacademy-javascript/2067857-keksobooking-26 pull request #6
Opened 2022-07-04 05:37 UTC by YaninaGazizovna

2022-07-04 15:00 UTC, Manyaka requested changes

2022-07-04 15:00 UTC, Manyaka commented on js/data.js
> +export {createProposals};
Экспорт пишется 1 раз, а внутри через запятую пишется то, что экспортируется

2022-07-04 15:00 UTC, Manyaka commented on js/popup.js
> +const similarCard=createProposals();
код надо или бьютифить или преттиером пользоваться. Если надо настроить - можем созвониться

2022-07-07 04:45 UTC, Manyaka requested changes

2022-07-07 04:45 UTC, Manyaka commented on js/data.js
на 19 строке удали пустой адрес

2022-07-07 04:45 UTC, Manyaka commented on js/popup.js
> +const cardTemaplate = document.querySelector('#card').content.querySelector('.popup');
```suggestion
const cardTemplate = document.querySelector('#card').content.querySelector('.popup');
```

поставь проверку орфографии

2022-07-07 04:45 UTC, Manyaka commented on js/popup.js
> +const similarCard = createProposals();
что возвращает createProposals()? Предложения - предложения это мн. ч., значит никак не может быть одна карточка, ну и similar - бессмысленно, на кого карточка похожа? ни на кого

2022-07-07 04:45 UTC, Manyaka commented on js/popup.js
> +  cardElement.querySelector('.popup__description').classList.add('hidden');
причеши красиво, тебе бы понравилось читать текст без абзацев?

2022-07-07 04:45 UTC, Manyaka commented on js/popup.js
> +  for (let image = 0; image <= proposal.offer.photos.length - 1; image++) {
смысла использовать слово image нет, потому что i - означает итерация - итерация цикла, и больше другого смысла у неё нет.

2022-07-07 04:45 UTC, Manyaka commented on js/popup.js
> +  cardElement.querySelectorAll('.popup__feature').forEach((featuresListItem) => {
дом ноду вынести в переменную сначала, а потом по ней итерируйся

2022-07-07 04:45 UTC, Manyaka commented on js/popup.js
> +  cardElement.querySelector('.popup__description').classList.add('hidden');
Хотя, лучше даже не причеши, а разбей на функции, так будет ещё нагляднее

2022-07-07 06:29 UTC, YaninaGazizovna commented on js/popup.js
> +  for (let image = 0; image <= proposal.offer.photos.length - 1; image++) {
done

2022-07-07 06:29 UTC, YaninaGazizovna commented on js/popup.js
> +const cardTemaplate = document.querySelector('#card').content.querySelector('.popup');
done

2022-07-07 06:29 UTC, YaninaGazizovna commented on js/data.js
done, но в прошлый раз мы говорили, что нужно оставить пустой массив в ключе

2022-07-07 06:41 UTC, YaninaGazizovna commented on js/popup.js
> +const similarCard = createProposals();
изменила на proposalCard, оставила в ед. ч., так как карта может быть и 1(как в текущем случае),a предложений, соответсвенно, может быть бесконечное множество , кажется, логично;)

2022-07-08 06:09 UTC, Manyaka requested changes

2022-07-08 06:09 UTC, Manyaka commented on js/popup.js
> +const similarCard = createProposals();
ну карточка то одна, но ты не можешь ходить в цикле по карточке, если она одна, так что нелогично, что тут в единственном числе, тогда как эта переменная содержит в себе массив, а как мы знаем из критерия, массивы мы называем во мн.ч.

2022-07-08 06:09 UTC, Manyaka commented on js/data.js
ну да, а ещё люди думали, что земля плоская, а потом передумали, когда у них поднакопилось опыта. Так что коллизии никакой нет: ты причесываешь код каждый раз, когда в него заходишь. Есть такое правило у программистов: правило бойскаута (https://habr.com/ru/company/piter/blog/431670/ тут можешь почитать)

2022-07-08 06:09 UTC, Manyaka commented on js/popup.js
> +  cardElement.querySelector('.popup__description').classList.add('hidden');
нужно тут проверку добавить, что если дескрипшена нет, тогда только хидден класс

2022-07-08 06:42 UTC, Manyaka requested changes

2022-07-08 06:42 UTC, Manyaka commented on js/popup.js
> +    const PhotoTemplate = document.querySelector('#card').content.querySelector('.popup__photo');
почему с большой буквы? это обычная переменная

2022-07-08 06:42 UTC, Manyaka commented on js/popup.js
> +  const GUESTS = proposal.offer.guests;
это не константы. Почему? - тебе надо ответить на вопрос, почему это не константы

2022-07-08 06:42 UTC, Manyaka commented on js/util.js
> +function getNumWord(value, word) {
название функции неудачное - получить цифро-слово? переведи тупо "множественное число" на английский - это будет "plural", и используй - получить множественное число слова - getPluralWord

2022-07-08 06:42 UTC, Manyaka commented on js/util.js
> +  return word[2];
ещё 0 надо

2022-07-08 06:42 UTC, Manyaka commented on js/popup.js
> +  ])} для ${GUESTS}${getNumWord(GUESTS, [' гостя', ' гостей', ' гостей'])}`;
массивы слов вынеси в константные массивы как раз, тк они не изменятся, пока ты сама не поправишь

2022-07-08 06:42 UTC, Manyaka commented on js/data.js
> +const createProposals = () => Array.from({ length: SIMILAR_PROPOSAL_COUNT }, createProposal);
А что если вместо функции сделать переменную?

2022-07-08 06:42 UTC, Manyaka commented on js/data.js
> +  DESCRIPTION:[ 'Incredible location,lovely restaurant,friendly welcome, kindness staff'],
пробел после двоеточия (а говорила преттиером прошлась)

2022-07-08 06:42 UTC, Manyaka commented on js/popup.js
> +  const typeArray = proposal.offer.type.split();
Зачем тебе тут сплит? Какая у тебя тут идея?

2022-07-08 06:42 UTC, Manyaka commented on js/popup.js
> +  });
Зачем тут цикл, когда тип дома приезжает один? 

Как можно вытащить значение объекта, когда мы знаем его ключ?

2022-07-08 06:42 UTC, Manyaka commented on js/popup.js
> +  });
тут какая-то странная сложна конструкция в проверкой на необходимость. Какой смысл в этой проверке?

2022-07-08 06:42 UTC, Manyaka commented on js/popup.js
> +  });
Как думаешь, можно фичи заппендить в карточку аналогично фоткам?

2022-07-09 04:42 UTC, YaninaGazizovna commented on js/popup.js
> +  const GUESTS = proposal.offer.guests;
потому как значения не статичные

2022-07-09 04:49 UTC, Manyaka commented on js/popup.js
> +  const GUESTS = proposal.offer.guests;
точно

2022-07-09 04:59 UTC, Manyaka requested changes

2022-07-09 04:59 UTC, Manyaka commented on js/data.js
> +const ROOM_WORD_ARRAY = [' комната ', ' комнаты ', ' комнат '];
только пробелы вытащи из "комнат", пробелы добавишь там где надо, а не тут: что если в другой части кода тебе нужно будет закончить на слове "комнат." с точкой, куда пробел будешь девать?

2022-07-09 04:59 UTC, Manyaka commented on js/data.js
> +const ROOM_WORD_ARRAY = [' комната ', ' комнаты ', ' комнат '];
Слово array лишнее, массивы мы обозначаем множественным числом

2022-07-09 04:59 UTC, Manyaka commented on js/popup.js
> +  if (!proposal.offer.description) {
да, правильно тут проверила на пустоту

2022-07-09 04:59 UTC, Manyaka commented on js/popup.js
> +  }
зачем цикл? Тип дома в единственном числе. Вытащи значение из объекта по ключу и всё.

2022-07-09 04:59 UTC, Manyaka commented on js/popup.js
> +    }
проверка не тут, айтем у тебя всегда будет, смысла нет тут проверять. Если хочешь проверить, что фичи вообще есть, проверять надо на уровень выше, даже на 2 уровня - при вызове функции, что если фич нет - смысл функцию вызывать (джава скрипт ещё гонять вхолостую), надо просто удалить заглушку и всё.

2022-07-11 05:08 UTC, Manyaka requested changes

2022-07-11 05:08 UTC, Manyaka commented on js/data.js
> +const GUEST_WORDS = [' гостя', ' гостей', ' гостей'];
пробелы в словах, надо удалить

2022-07-11 05:08 UTC, Manyaka commented on js/util.js
> +  if (value > 1 && value < 5 && value === 0) {
проверь условия, точно тут "И"? Потому что 0 не может быть больше 1

2022-07-11 08:17 UTC, merged